### ISSUE TITLE
Erro ao tirar selfie com Localização Ligada

### ISSUE THREAD

**Issue by abreudiego94** [acesso-io/unico-check-flutter#54]
Ao tirar selfie com a Localização Ligada o SDK simplesmente para de funcionar, porém ao tirar com a Localização desligada o erro não aparece..

 java.lang.NullPointerException: geocoder.getFromLocation…ngitude, 1)[0].postalCode must not be null
E/AndroidRuntime( 3225):        at com.acesso.acessobio_android.u2.onLocationChanged(LocationListenerImpl.kt:14)
E/AndroidRuntime( 3225):        at android.location.LocationListener.onLocationChanged(LocationListener.java:63)
E/AndroidRuntime( 3225):        at android.location.LocationManager$LocationListenerTransport$1.operate(LocationManager.java:3180)
E/AndroidRuntime( 3225):        at android.location.LocationManager$LocationListenerTransport$1.operate(LocationManager.java:3177)
E/AndroidRuntime( 3225):        at com.android.internal.listeners.ListenerExecutor.lambda$executeSafely$0(ListenerExecutor.java:127)
E/AndroidRuntime( 3225):        at com.android.internal.listeners.ListenerExecutor$$ExternalSyntheticLambda0.run(Unknown Source:8)
E/AndroidRuntime( 3225):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 3225):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3225):        at android.os.Looper.loopOnce(Looper.java:210)
E/AndroidRuntime( 3225):        at android.os.Looper.loop(Looper.java:299)
E/AndroidRuntime( 3225):        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by octaviodivy** [comment]
Estou com um problema muito parecido mas no nosso caso é após autorizar localização. Android e iOS
